name: "Check self-hosted runner (local)"
description: "Checks for an online, not-busy self-hosted runner with a given label and emits outputs `available` and `count`."
inputs:
  label:
    description: "Optional label to probe (overrides PREF env)"
    required: false
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
      with:
        node-version: '20'

    - name: Run check script
      shell: bash
      env:
        INPUT_LABEL: ${{ inputs.label }}
        PREF: ${{ vars.PREF_RUNNER || secrets.PREF_RUNNER }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        # Use the repo-local script to query the Actions API and write outputs
        node ./.github/actions/check-runner/check-runner.js
        echo "available=$(cat .runner-output-available || echo false)" >> $GITHUB_OUTPUT || true
        echo "count=$(cat .runner-output-count || echo 0)" >> $GITHUB_OUTPUT || true
        rm -f .runner-output-available .runner-output-count || true