name: "CI - Build"
description: "Composite action for building the application and uploading artifact when tagged."
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608

    - name: Setup Node.js
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
      with:
        node-version: '20'
        cache: 'npm'

    - name: Cache Next.js build
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
      with:
        path: |
          ~/.npm
          ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
          ${{ runner.os }}-nextjs-

    - name: Install dependencies
      run: |
        npm config set update-notifier false
        npm ci

    - name: Build application
      env:
        NEXT_PUBLIC_CLARITY_ID: ${{ secrets.NEXT_PUBLIC_CLARITY_ID }}
      run: npm run build

    - name: Upload build artifacts
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
      with:
        name: ta-cukrarna-build
        path: |
          out/
          package.json
          package-lock.json
        retention-days: 1
